FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential ca-certificates git libglpk-dev libgmp-dev m4 \
       patch pkg-config unzip wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget -q \
      https://github.com/ocaml/opam/releases/download/2.0.8/opam-2.0.8-x86_64-linux \
      -O /usr/local/bin/opam \
    && echo "95365a873d9e3ae6fb48e6109b5fc5df3b4e526c9d65d20652a78e263f745a35  /usr/local/bin/opam" \
       | sha256sum -c - \
    && chmod 755 /usr/local/bin/opam

RUN opam init -y --disable-sandboxing --bare \
    && opam switch create polcert 4.13.1 \
    && opam install -y --switch=polcert \
       coq.8.13.2 dune.3.22.2 glpk.0.1.8 menhir.20260209 \
       ocamlfind.1.9.8 stdlib-shims.0.3.0 zarith.1.14

COPY source /polcert
WORKDIR /polcert
RUN eval "$(opam env --switch=polcert)" \
    && ./configure x86_64-linux \
    && make depend \
    && make -j2 proof \
    && make -s check-admitted \
    && make extraction
